sudo: required
language: node_js
node_js:
  - "stable"

services: mongodb

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm start &
  - sleep 5 # give server some time to start
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
script:
  - npm test
